# Generated by Django 5.1 on 2024-09-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourseregistration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
