# Generated by Django 5.1 on 2025-05-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourseregistration', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('mc', 'Mass Communication'), ('journalism', 'Journalism'), ('eee', 'Electrical Electronics Engineering'), ('ba', 'Business Administration'), ('se', 'Software Engineering')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd')], max_length=3, null=True),
        ),
    ]
