# Generated by Django 5.1 on 2025-06-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourseregistration', '0004_customuser_department_customuser_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('cs', 'Computer Science'), ('mc', 'Mass Communication'), ('journalism', 'Journalism'), ('eee', 'Electrical Electronics Engineering'), ('ba', 'Business Administration'), ('se', 'Software Engineering')], max_length=50)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=3)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=3)),
                ('credit_units', models.IntegerField()),
            ],
        ),
    ]
